### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventLocator using 5.0.0 version of wmts-v_1_0

### ISSUE THREAD

**Issue by MarkARussell** [ogc-schemas/ogc-schemas#9]
I'm seeing a `java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventLocator` error when trying to use the wmts-v_1_0 library in an environment where only the jakarta.xml.bind APIs are available.  Per the changelog 5.0.0 was transitioned to use the jakarta API's.  

It looks like the root cause of this is that the projects still depend on the org.jvnet runtime library `org.jvnet.jaxb2_commons:jaxb2-basics-runtime` which uses the javax.xml.bind packages internally.  It does look like they have create a new 3.0 compatible version of the maven plugin and related libraries (see https://github.com/highsource/jaxb-tools).  Though it also looks like the groupId and artifactIds have changed for a bunch of the projects.

**Comment by laurentschoelens** [comment]
@MarkARussell 

Yes you're right about jaxb-tools
@soc is currently working on integrating the v3 version here
If you have any questiols regarding migration, you should check this [guide](https://github.com/highsource/jaxb-tools/wiki/JAXB-Tools-Migration-Guide) and create issue if not complete
We'd be happy to help

Laurent

**Comment by soc** [comment]
Hi @MarkARussell,

I'm trying to get a proper 5.0.1 release of ogc-schemas out, it's currently blocked by https://github.com/highsource/jaxb-tools/issues/434. w3c-schemas (3.0.1) should already be fine.

**Comment by soc** [comment]
@MarkARussell 5.0.1 is published, please give it a try and report back!

**Comment by MarkARussell** [comment]
Yep tested the new versions of gml, qws, wmts, and xlink and they all seem to be working fine for me now.  Thanks.

**Comment by soc** [comment]
Nice, thanks for checking!
